<?php

use Phalcon\Forms\Form;
use Phalcon\Forms\Element\Text;
use Phalcon\Forms\Element\Password;
use Phalcon\Validation;
use Phalcon\Validation\Validator\Email;
use Phalcon\Validation\Validator\PresenceOf;


$form = new Form();

$first = new Text("First Name");
$last = new Text("Last Name");
$email = new Email();
$username = new Text("Username");
$password = new Password('password', [
            'class' => 'form-control input-md',
            'placeholder' => 'Password'
        ]);
        
// Validators

$validation = new Validation();
        
$validation->add(
    'name',
    new PresenceOf(
        [
            'message' => 'The name is required',
        ]
    )
);

$validation->add(
    'email',
    new PresenceOf(
        [
            'message' => 'The e-mail is required',
        ]
    )
);

$validation->add(
    'email',
    new Email(
        [
            'message' => 'The e-mail is not valid',
        ]
    )
);

$first->addValidator($validation);
$last->addValidator($validation);
$email->addValidator($validation);


$form->add($first);
$form->add($last);
$form->add($email);
$form->add($username);
$form->add($password);




$messages = $validation->validate($_POST);

if (count($messages)) {
    foreach ($messages as $message) {
        echo $message, '<br>';
    }
}

?>




<h2>Sign up using this form</h2>

<section class="main-container">
    <div class="main-wrapper">
        <h2>Signup</h2>
        <form class="signup-form" action="" method="POST">
            <input type="text" name="first" placeholder="First name">
            <input type="text" name="last" placeholder="Last name">
            <input type="text" name="email" placeholder="E-mail">
            <input type="text" name="uid" placeholder="Username">
            <input type="password" name="pwd" placeholder="password">
            <button type="submit" name="submit" value="set">Sign Up</button>
        </form>
    </div>
</section>




