<h2>Sign up using this form</h2>

<section class="main-container">
    <div class="main-wrapper">
        <h2>Signup</h2>
        
        <form class="signup-form" action="" method="POST">
            <p>
                <label> First Name </label>
                <?php echo $form->render('first_name'); ?>
            </p>
            <p>
                <label> Last Name </label>
                <?php echo $form->render('last_name'); ?>
            </p>
            <p>
                <label> Username </label>
                <?php echo $form->render('username'); ?>
            </p>
            <p>
                <label> Password </label>
                <?php echo $form->render('password'); ?>
            </p> 
            <button type="submit" name="submit" value="set">Sign Up</button>
        </form>
    </div>
</section>
